#!/usr/bin/env python3

# Copyright (c) 2026, Synopsys, Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3) Neither the name of the Synopsys, Inc., nor the names of its contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import argparse
import logging
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.INFO)

@dataclass
class PrepareGate1Configuration:
    triplet: str
    gcc_binary_path: str
    workspace_dir_path: str
    gcc_sources_dir_path: str
    picolibc_sources_dir_path: str

@dataclass
class PrerequisitesGeneratorConfiguration:
    triplet: str
    build_log_path: str
    build_dir_path: str
    gcc_sources_dir_path: str
    picolibc_sources_dir_path: str
    buildlib_dir_path: str


@dataclass
class BuilderConfiguration:
    triplet: str
    buildlib_dir_path: str
    install_dir_path: str
    cflags: str

#
# Prepare stage 1 code.
#

PREPARE_STAGE1_DIR_NAME = 'stage1'
PREPARE_STAGE1_NPROC = 4

def prepare_stage1(cfg: PrepareGate1Configuration):
    # Locate target's include directory. It's required for building GCC's libraries.
    toolchain_root_dir_path = Path(cfg.gcc_binary_path).parent.parent
    include_dir_path = toolchain_root_dir_path.joinpath(cfg.triplet, "include")

    if not include_dir_path.exists():
        logging.error("Include directory for the toolchain does not exist: %s", include_dir_path)

    logging.info("Found include directory for the toolchain: %s", include_dir_path)

    # Create a stage 1 directory.
    stage1_dir_path = Path(cfg.workspace_dir_path).joinpath(PREPARE_STAGE1_DIR_NAME).absolute()
    stage1_dir_path.mkdir(parents=True)
    logging.info('Creating a workspace directory for stage 1: %s', stage1_dir_path)

    # Create a link to GCC sources so we will be able to use relative paths
    # while building libraries.
    gcc_sources_path_link = stage1_dir_path.joinpath('gcc')
    gcc_sources_path_link.symlink_to(cfg.gcc_sources_dir_path, True)
    logging.info('Creating a symbolic link to GCC sources: %s', cfg.gcc_sources_dir_path)

    # Create a link to Picolibc sources. It will be used on stage 2.
    picolibc_sources_path_link = stage1_dir_path.joinpath('picolibc')
    picolibc_sources_path_link.symlink_to(cfg.picolibc_sources_dir_path, True)
    logging.info('Creating a symbolic link to Picolibc sources: %s', cfg.picolibc_sources_dir_path)

    # Create a build directory.
    build_dir_path = stage1_dir_path.joinpath('build')
    build_dir_path.mkdir()
    logging.info('Creating a build directory for stage 1: %s', build_dir_path)

    # Construct an install directory path. It's not required further but we should
    # prevent make from trying to put headers to host's directories.
    install_dir_path = stage1_dir_path.joinpath('install')

    # Add a toolchain's GCC binary to PATH to make it visible for configure and make.
    env = os.environ.copy()
    env['PATH'] = '{}:{}'.format(os.path.dirname(cfg.gcc_binary_path), env['PATH'])

    # Now we are going to configure GCC for a random non-multilib target. We need it
    # only for logs so it does not matter what particular target is used.
    arguments = [
        '../gcc/configure',
        '--target={}'.format(cfg.triplet),
        '--prefix={}'.format(install_dir_path),
        '--disable-shared',
        '--disable-threads',
        '--enable-languages=c,c++',
        '--enable-tls',
        '--with-newlib',
        '--with-headers={}'.format(include_dir_path),
        '--disable-libmudflap',
        '--disable-libssp',
        '--disable-libquadmath',
        '--disable-libgomp',
        '--disable-nls',
        '--disable-tm-clone-registry',
        '--disable-multilib',
        '--with-arch=rv32imac',
        '--with-abi=ilp32',
        '--with-tune=rocket',
        '--with-cmodel=medlow',
        '--with-isa-spec=20191213'
    ]

    with open(stage1_dir_path.joinpath('config.log'), 'w', encoding='utf-8') as log_file:
        command = ' '.join(arguments)
        logging.info('Configuring GCC:\n%s', command)
        log_file.write(command + '\n')
        log_file.flush()

        result = subprocess.run(arguments, stdout=log_file, stderr=subprocess.STDOUT, encoding='utf-8', env=env, cwd=build_dir_path)

        if result.returncode != 0:
            logging.error("Configuring of GCC failed, check the log file.")
            sys.exit(1)

    # Now we are ready to build libgcc and libstdc++.
    arguments = [
        'make',
        '-j',
        str(PREPARE_STAGE1_NPROC),
        'all-target-libgcc',
        'all-target-libstdc++-v3'
    ]

    with open(stage1_dir_path.joinpath('build.log'), 'w', encoding='utf-8') as log_file:
        command = ' '.join(arguments)
        logging.info('Building GCC libraries:\n%s', command)
        log_file.write(command + '\n')
        log_file.flush()

        result = subprocess.run(arguments, stdout=log_file, stderr=subprocess.STDOUT, encoding='utf-8', env=env, cwd=build_dir_path)

        if result.returncode != 0:
            logging.error("Building of GCC libraries failed, check the log file.")
            sys.exit(1)

    logging.info('Finished building of GCC libraries.')


def find_library_object_files(library_path: str) -> list[str]:
    result = subprocess.run(["ar", "-t", library_path], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding="utf-8")

    if result.returncode != 0:
        logging.error("Error while retrieving object files from %s:\n%s", library_path, result.stdout)
        sys.exit(1)

    return sorted(result.stdout.split())


def find_multiline_object_build_command(object_file_name: str, libgcc_build_log: str) -> str:
    grep_after_lines = 0

    while True:
        # All target object files are built with extra -MT argument. We should
        # rely on this behavior to filter objects files with the same names but
        # not related to target code.
        arguments = [
            "grep",
            "-A {}".format(grep_after_lines),
            "\\-o {} \\-MT".format(object_file_name),
            libgcc_build_log,
        ]
        result = subprocess.run(arguments, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding="utf-8")

        if result.returncode != 0:
            logging.error("Error while searching a build ling in logs:\n%s", result.stdout)
            sys.exit(1)

        build_command = result.stdout.strip()

        # Some original build commands may be present as a multiline
        # with "\" endings in the original Makefile. If we encounter a build
        # command with "\" then we should grab extra lines from a build log.
        if build_command.endswith("\\"):
            grep_after_lines += 1
        else:
            return " ".join(build_command.replace("\\", "").splitlines())


def parse_dep_file_dependencies(dep_file_path: str) -> list[str]:
    logging.info("Analyzing dependencies file: %s.", dep_file_path)

    dep_file_path = Path(dep_file_path)
    dep_file_name = dep_file_path.name

    # We put all dependency from a .dep file to a set to exclude duplications.
    dependencies = set()

    # We need to perform these transformations on .dep lines to convert them
    # to clean paths:
    #
    #     1. Remove .o target (the object file itself).
    #     2. Remove all ":" and "\" symbols
    #     3. Remove dependencies with "sys-include" - they could be found in
    #        a prebuilt GCC for RISC-V.
    #     4. Convert all relative paths to absolute paths.
    #     5. Add dependencies to a set to eliminated duplications.
    with open(dep_file_path, "r", encoding="utf-8") as f:
        for path in f.readlines():
            chunks = path.strip().split()

            for chunk in chunks:
                chunk = chunk.strip()

                logging.debug("Analyzing .dep file: %s: analyzing dependency %s", dep_file_name, chunk)

                # .dep file is Makefile. Remove a target for an object file itself and
                # "\" symbols for lists of dependencies.
                if chunk.endswith("o:") or chunk == "\\":
                    continue

                # Remove headers from sys-include. Precompiled GCC will use
                # its own headers.
                if "sys-include" in chunk:
                    continue

                # Most dependencies are just empty make rules. Just remove ":".
                if chunk.endswith(":"):
                    chunk = chunk[:-1]

                if not Path(chunk).is_absolute():
                    chunk = dep_file_path.parent.joinpath(chunk)

                    # If it's a symlink then add both the symlink and
                    # the original file.
                    if not chunk.is_symlink():
                        chunk = chunk.resolve()
                    else:
                        dependencies.add(str(chunk.resolve()))

                    chunk = str(chunk)

                dependencies.add(chunk)

                logging.debug("Analyzing .dep file: %s: adding dependency %s", dep_file_name, chunk)

    return sorted(list(dependencies))


def parse_gcc_version(gcc_executable: str) -> str:
    result = subprocess.run([gcc_executable, "--version"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding="utf-8")

    if result.returncode != 0:
        logging.error("Error while parsing GCC's version:\n%s", result.stdout)
        sys.exit(1)

    return result.stdout.strip().splitlines()[0].split()[-1].strip()

def generate_buildlib_workspace():
    pass

# This functions works only for libgcc so far.
def generate_libgcc_prerequisites(cfg: PrerequisitesGeneratorConfiguration):
    logging.info("Generating prerequisites for libgcc.")

    # Retrieve a list of all .o files in a library.
    libgcc_library_path = Path(cfg.build_dir_path).joinpath(cfg.triplet, "libgcc", "libgcc.a")
    libgcc_object_file_names = find_library_object_files(libgcc_library_path)

    # Add crt*.o object files from libgcc bundle too.
    crt_object_file_names = ["crtbegin.o", "crtend.o", "crti.o", "crtn.o"]

    # Add all object files to a single list.
    all_object_file_names = libgcc_object_file_names + crt_object_file_names
    logging.debug("Retrieved this list of object files:\n%s", str(all_object_file_names))

    # Convert all object files to .dep files with .c and .h dependencies.
    dep_file_names = list(map(lambda name: name.replace(".o", ".dep"), all_object_file_names))
    logging.debug("Retrieved this list of dep files:\n%s", str(dep_file_names))

    # Retrieve of dependencies from all .dep files.
    dependencies = set()

    for dep_file_name in dep_file_names:
        dep_file_path = libgcc_library_path.parent.joinpath(dep_file_name)
        dependencies.update(parse_dep_file_dependencies(dep_file_path))

    dependencies = sorted(list(dependencies))
    logging.debug("The final list of dependencies:\n%s", "\n".join(dependencies))

    # Prepare output directories.
    output_dir_path = Path(cfg.buildlib_dir_path)
    output_dir_path.mkdir(parents=True, exist_ok=True)
    output_build_dir_path = output_dir_path.joinpath("build")
    output_build_dir_path.mkdir(exist_ok=True)
    output_sources_dir_path = output_dir_path.joinpath("gcc")
    output_sources_dir_path.mkdir(exist_ok=True)

    # Copy all dependencies to a separate directory.
    for source_dependency_file_path in dependencies:
        source_dependency_file_path = Path(source_dependency_file_path)

        # An original dependency must reside in sources or build directory.
        # Otherwise we've encountered a faulty path.
        if source_dependency_file_path.is_relative_to(cfg.build_dir_path):
            destination_dependency_file_path = output_build_dir_path.joinpath(source_dependency_file_path.relative_to(cfg.build_dir_path))
        elif source_dependency_file_path.is_relative_to(cfg.gcc_sources_dir_path):
            destination_dependency_file_path = output_sources_dir_path.joinpath(source_dependency_file_path.relative_to(cfg.gcc_sources_dir_path))
        else:
            logging.error("Dependency is not in build or source directory: %s", source_dependency_file_path)
            sys.exit(1)

        destination_dependency_file_path.parent.mkdir(parents=True, exist_ok=True)

        if destination_dependency_file_path.exists():
            os.remove(destination_dependency_file_path)

        shutil.copy(source_dependency_file_path, destination_dependency_file_path, follow_symlinks=False)

    # Create a skeleton of Makefile for libgcc.
    makefile_path = Path(output_build_dir_path).joinpath(cfg.triplet, "libgcc", "Makefile")
    logging.info("Opening Makefile for write for libgcc: %s", makefile_path)
    makefile_file = makefile_path.open(mode="w", encoding="utf-8")
    makefile_file.writelines(
        [
            ".PHONY: all install clean\n\n",
            "TRIPLET ?= {}\n".format(cfg.triplet),
            "GCC ?= $(TRIPLET)-gcc\n",
            "DESTDIR ?= ../../../install\n",
            "INSTALL_SUBDIR := lib/gcc/$(TRIPLET)/$(shell $(GCC) -dumpfullversion)\n"
            "OBJECTS_LIBGCC := {}\n".format(" ".join(libgcc_object_file_names)),
            "OBJECTS_CRT := {}\n".format(" ".join(crt_object_file_names)),
            "OBJECTS_ALL := $(OBJECTS_LIBGCC) $(OBJECTS_CRT)\n\n",
            "all: libgcc.a $(OBJECTS_ALL)\n\n",
            "install: libgcc.a $(OBJECTS_CRT)\n",
            "\tmkdir -p $(DESTDIR)/$(INSTALL_SUBDIR)\n",
            "\tcp -f $^ $(DESTDIR)/$(INSTALL_SUBDIR)\n\n",
            "clean:\n",
            "\trm -f libgcc.a $(OBJECTS_ALL)\n\n",
            "libgcc.a: $(OBJECTS_LIBGCC)\n",
            "\triscv64-snps-elf-ar rc $@ $^\n",
            "\triscv64-snps-elf-ranlib $@\n\n",
        ]
    )

    # Find a build line in libgcc's build log for each object file.
    for object_file_name in all_object_file_names:
        build_command = find_multiline_object_build_command(object_file_name, cfg.build_log_path)
        logging.debug("Build line for %s:\n%s", object_file_name, build_command)

        build_command_arguments = []
        is_isystem = False
        is_mt_mf = False

        # Remove extra and duplicated arguments.
        for chunk in build_command.split():
            if chunk.endswith("xgcc") or chunk.startswith("-B"):
                # We are not going to use xgcc from the original build and
                # extra -B include flags.
                continue
            elif chunk in ["-MD", "-MP", "-g", "-O0", "-O1", "-O2", "-O3", "-Ofast", "-Os"]:
                # Skip all unnecessary and optimization options from the original build.
                continue
            elif chunk == "-isystem":
                # We don't need -isystem includes. GCC will use includes from
                # a prebuilt bundle.
                is_isystem = True
            elif is_isystem:
                is_isystem = False
            elif chunk in ["-MT", "-MF"]:
                # We can skip -MT and -MF with its arguments.
                is_mt_mf = True
            elif is_mt_mf:
                is_mt_mf = False
            else:
                # Add a flag to the final build command if it's not duplicated.
                if chunk not in build_command_arguments:
                    build_command_arguments.append(chunk)

        # Craft a final build command and append CFLAGS for extra
        # target argument.
        build_command = "$(GCC) {} $(CFLAGS)".format(" ".join(build_command_arguments))

        # Now we have a build command for a object file. Add it to a Makefile.
        makefile_target = "{}:\n\t{}\n\n".format(object_file_name, build_command)
        makefile_file.write(makefile_target)
        logging.debug("Final build command for %s:\n%s", object_file_name, build_command)

    makefile_file.close()


def generate_picolibc_prerequisites(cfg: PrerequisitesGeneratorConfiguration):
    logging.info("Generating prerequisites for Picolibc.")
    shutil.copytree(cfg.picolibc_sources_dir_path, os.path.join(cfg.buildlib_dir_path, "picolibc"))


def build_libgcc(cfg: BuilderConfiguration):
    libgcc_dir_path = Path(cfg.buildlib_dir_path).joinpath("build", cfg.triplet, "libgcc").resolve()

    arguments = 'make install CFLAGS="{}" DESTDIR="{}"'.format(cfg.cflags, cfg.install_dir_path)
    logging.info("Building a configuration: %s", arguments)

    if logging.getLogger().getEffectiveLevel() == logging.DEBUG:
        result = subprocess.run(arguments, encoding="utf-8", cwd=str(libgcc_dir_path), shell=True)

        if result.returncode != 0:
            logging.error("Error while building libgcc.")
            sys.exit(1)
    else:
        result = subprocess.run(arguments, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding="utf-8", cwd=str(libgcc_dir_path), shell=True)

        if result.returncode != 0:
            logging.error("Error while building libgcc:\n%s", result.stdout)
            sys.exit(1)

ARGPARSE_COMMAND_PREPARE_STAGE1 = "prepare-stage1"
ARGPARSE_COMMAND_PREPARE_STAGE2 = "prepare-stage2"
ARGPARSE_COMMAND_BUILD = "build"


def main():
    # Derive a triplet from script's name and try to locate a path to a GCC binary.
    triplet = os.path.basename(__file__).rsplit("-", maxsplit=1)[0]

    gcc_binary_name = '{}-gcc'.format(triplet)
    gcc_binary_path = shutil.which(gcc_binary_name)

    if gcc_binary_path:
        logging.info("Found GCC in PATH: %s", gcc_binary_path)
    else:
        gcc_binary_path = Path(__file__).parent.joinpath(gcc_binary_name)
        if gcc_binary_path.exists():
            logging.info("Found GCC in a local directory: %s", str(gcc_binary_path))
        else:
            logging.error("Cannot find GCC in PATH or in a local directory.")
            return 1

    # Create command line arguments parsers for these commands:
    #
    #     prepare-stage1
    #     prepare-stage2
    #     build
    #

    parser = argparse.ArgumentParser(prog=os.path.basename(__file__), description="Buildlib for ARC-V GNU toolchain.")
    parser.add_argument("--debug", action="store_true")
    subparsers = parser.add_subparsers(dest="command")

    parser_prepare = subparsers.add_parser(ARGPARSE_COMMAND_PREPARE_STAGE1, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_prepare.add_argument("--workspace-dir-path", type=str, required=True, metavar="PATH")
    parser_prepare.add_argument("--gcc-sources-dir-path", type=str, required=True, metavar="PATH")
    parser_prepare.add_argument("--picolibc-sources-dir-path", type=str, required=True, metavar="PATH")

    parser_prepare = subparsers.add_parser(ARGPARSE_COMMAND_PREPARE_STAGE2, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_prepare.add_argument("--build-log-path", type=str, required=True, metavar="PATH")
    parser_prepare.add_argument("--build-dir-path", type=str, required=True, metavar="PATH")
    parser_prepare.add_argument("--gcc-sources-dir-path", type=str, required=True, metavar="PATH")
    parser_prepare.add_argument("--picolibc-sources-dir-path", type=str, required=True, metavar="PATH")
    parser_prepare.add_argument(
        "--buildlib-dir-path", type=str, default="buildlib", metavar="PATH", help="Output directory for buildlib prerequisites"
    )
    parser_prepare.add_argument("--tmp-dir-path", type=str, default="tmp", metavar="PATH", help="A temporary directory for build files")
    parser_prepare.add_argument("--no-build", action="store_true", help="Skip a build stage")
    parser_prepare.add_argument("--triplet", type=str, default=triplet, help="A toolchain triplet")
    parser_prepare.add_argument("--clean", action="store_true")

    parser_build = subparsers.add_parser(ARGPARSE_COMMAND_BUILD, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_build.add_argument("--buildlib-dir-path", type=str, default="buildlib", metavar="PATH", help="Path to buildlib prerequisites")
    parser_build.add_argument("--install-dir-path", type=str, default="output", metavar="PATH", help="Path to the output directory")
    parser_build.add_argument("--cflags", type=str, default="-g -O2", metavar="CFLAGS", help="Extra target flags for GCC")
    parser_build.add_argument("--triplet", type=str, default=triplet, help="A toolchain triplet")
    parser_build.add_argument("--no-libgcc", action="store_true")
    parser_build.add_argument("--no-libstdc++", action="store_true")
    parser_build.add_argument("--no-picolibc", action="store_true")

    args = parser.parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.command is None:
        print(parser.print_help())
    elif args.command == ARGPARSE_COMMAND_PREPARE_STAGE1:
        cfg = PrepareGate1Configuration(
            triplet=triplet,
            gcc_binary_path=gcc_binary_path,
            workspace_dir_path=os.path.abspath(args.workspace_dir_path),
            gcc_sources_dir_path=os.path.abspath(args.gcc_sources_dir_path),
            picolibc_sources_dir_path=os.path.abspath(args.picolibc_sources_dir_path)
        )

        prepare_stage1(cfg)
    elif args.command == ARGPARSE_COMMAND_PREPARE_STAGE2:
        cfg = PrerequisitesGeneratorConfiguration(
            triplet=args.triplet,
            build_log_path=os.path.abspath(args.build_log_path),
            build_dir_path=os.path.abspath(args.build_dir_path),
            gcc_sources_dir_path=os.path.abspath(args.gcc_sources_dir_path),
            picolibc_sources_dir_path=os.path.abspath(args.picolibc_sources_dir_path),
            buildlib_dir_path=os.path.abspath(args.buildlib_dir_path),
        )

        if args.clean:
            logging.info("Removing buildlib directory: %s", cfg.buildlib_dir_path)
            if os.path.exists(cfg.buildlib_dir_path):
                shutil.rmtree(cfg.buildlib_dir_path)

        generate_libgcc_prerequisites(cfg)
        generate_picolibc_prerequisites(cfg)
    elif args.command == ARGPARSE_COMMAND_BUILD:
        cfg = BuilderConfiguration(
            triplet=args.triplet,
            buildlib_dir_path=os.path.abspath(args.buildlib_dir_path),
            install_dir_path=os.path.abspath(args.install_dir_path),
            cflags=args.cflags,
        )

        if not args.no_libgcc:
            build_libgcc(cfg)

    return 0


if __name__ == "__main__":
    sys.exit(main())
